### ISSUE TITLE
Ios10 encountered a bug

### ISSUE THREAD

**Issue by seekwe** [gao-sun/animator.js#2]
`.frame-1 { transform: translateZ(0) translateY(-100px);
.frame-2 { transform: translateZ(0) translateY(-50px); }
.frame-0 { transform: translateZ(0) translateY(0);}`

`let Frame = [];
Frame [0] = new frame ('.frame-1', { duration: 400, 'cubic-bezier(0,0,.7,0)'});
Frame [1] = new frame ('.frame-0', { duration: 400,'cubic-bezier(0,0,.35,1)'});
Frame [2] = new frame ('.frame-2', { duration: 400, 'cubic-bezier(0,0,.7,0)'});
Frame [3] = new frame ('.frame-0', { duration: 400, 'cubic-bezier(0,0,.35,1)'});
var q = new Queue(square, frames,{ applyOnEnd: true });
q.play();
`

Have the opportunity to stuck in an animation in the frame,

The following is no problem

`
var frames1= new frame ('.frame-1', 1000);
var frames2 = new frame ('.frame-2', 1000);
var q = new Queue(square, frames1,{ applyOnEnd: true });
q.play().then(()=>{
let q2 = new Queue(square, frames2,{ applyOnEnd: true });
q2.play()
})`

ps.Please forgive my English is not good

**Comment by gao-sun** [comment]
Thank you for submitting! I'll check it out tonight. :-)

**Comment by gao-sun** [comment]
I tested in iOS 10.3.1 and it works fine. Please make sure your syntax is correct since there are lots of mistakes in your snippet.

**Comment by seekwe** [comment]
@gao-sun 
demo video : http://demo.73zls.com/zls/test/animatorjs/demo.mp4
demo url : http://demo.73zls.com/zls/test/animatorjs/
ios  : 10.2

At present, only one iPhone7 plug encountered, my iphone6 and iphone se no problem (ios9), the video is a micro letter (please ignore), the last alert ok did not appear
If you can't reproduce it, it might just be a case
thanks

**Comment by gao-sun** [comment]
感谢你提供的视频和测试链接。我的手机也是iPhone 7 Plus, 昨天升级到了iOS 10.3.2。用你的链接在Chrome，Safari和微信内置浏览器中均测试了数次，动画效果正常并会弹出OK的alert。有可能是系统版本的原因。如果升级后还是有此情况麻烦再次留言告知。谢谢！

**Comment by seekwe** [comment]
经测试似乎只有10.2.1才有，把手机系统升级就没有了，猜测ios问题，跳过
